<a href="https://colab.research.google.com/github/ranshull/DRUG_DRUG-INTERACTION/blob/main/EDA_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EDA PROJECT

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/COLLAB FILES CSV/automobile_data.csv")
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [ ]:
np.nan

nan

In [ ]:
#replace ? with Nan
df.replace("?",np.nan,inplace=True)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [ ]:
df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [ ]:
# count vnull values
df.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [ ]:
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [ ]:
df.insert?

In [ ]:
#insert a new column "price_int"
# df.insert(5,"price_int",0)
# df

In [ ]:
# make data type of price int as int
df['price'] = pd.to_numeric(df['price'], errors='coerce').astype('float64')

In [ ]:
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                float64
dtype: object

In [ ]:
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                float64
dtype: object

In [ ]:
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950.0
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470.0
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [ ]:
df.replace("?",np.nan,inplace=True)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [ ]:
#handle null values
df["price"].fillna(df["price"].mean(),inplace=True)
df

/tmp/ipython-input-79-404008169.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["price"].fillna(df["price"].mean(),inplace=True)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950.0
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470.0
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [ ]:
#check null values in price
df["price"].isnull().sum()

np.int64(0)

In [ ]:
#group by comany and price
a=df.groupby("make").price.max()
a.

make
alfa-romero      16500.000000
audi             23875.000000
bmw              41315.000000
chevrolet         6575.000000
dodge            12964.000000
honda            12945.000000
isuzu            13207.129353
jaguar           36000.000000
mazda            18344.000000
mercedes-benz    45400.000000
mercury          16503.000000
mitsubishi       14869.000000
nissan           19699.000000
peugot           18150.000000
plymouth         12764.000000
porsche          37028.000000
renault           9895.000000
saab             18620.000000
subaru           11694.000000
toyota           17669.000000
volkswagen       13845.000000
volvo            22625.000000
Name: price, dtype: float64

In [ ]:
#b comany with highest prices
A=df[df['price']==df['price'].max()]

In [ ]:
B=df.sort_values(["price","make"],ascending=False)
B[['make',]]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
74,1,NaN,mercedes-benz,gas,std,two,hardtop,rwd,front,112.0,...,304,mpfi,3.8,3.35,8.0,184,4500,14,16,45400.0

In [112]:
#which company manufactured the most expensive car at which price?
max_hp = df.groupby('make')['price'].max()
max_hp.sort_values(ascending=False)
max_hp.idxmax()

'mercedes-benz'

In [113]:
#c calculate the mximum horsepower for each companu
df.groupby("make").horsepower.max()

make
alfa-romero      154
audi             160
bmw              182
chevrolet         70
dodge             88
honda             86
isuzu             90
jaguar           262
mazda             84
mercedes-benz    184
mercury          175
mitsubishi        88
nissan            97
peugot            97
plymouth          88
porsche          288
renault          NaN
saab             160
subaru            94
toyota            92
volkswagen        90
volvo            162
Name: horsepower, dtype: object

In [114]:
#d what is the total count of car manufactured by ecah comapny
df.groupby("make").make.count()

make
alfa-romero       3
audi              7
bmw               8
chevrolet         3
dodge             9
honda            13
isuzu             4
jaguar            3
mazda            17
mercedes-benz     8
mercury           1
mitsubishi       13
nissan           18
peugot           11
plymouth          7
porsche           5
renault           2
saab              6
subaru           12
toyota           32
volkswagen       12
volvo            11
Name: make, dtype: int64

In [119]:
#e)
#insert a coloumn at last
df.insert(10,'updated_prices',0)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950.0
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470.0
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [120]:
df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'updated_prices', 'length', 'width', 'height',
       'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size',
       'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower',
       'peak-rpm', 'city-mpg', 'highway-mpg', 'price'],
      dtype='object')

In [122]:
f[(df['engine-location'])=='rear']

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
126,3,NaN,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.9,9.5,207,5900,17,25,32528.0
127,3,NaN,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.9,9.5,207,5900,17,25,34028.0
128,3,NaN,porsche,gas,std,two,convertible,rwd,rear,89.5,...,194,mpfi,3.74,2.9,9.5,207,5900,17,25,37028.0

In [164]:
# find iloc of where rear is
# print(df.loc[df['engine-location']=='rear'])

for i in df['engine-location'].index:
   if df['engine-location'].iloc[i]=='rear':
    df['updated_prices'].iloc[i]=df['price'].iloc[i]*2
   else:
    df['updated_prices'].iloc[i]=df['price'].iloc[i]

/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['updated_prices'].iloc[i]=df['price'].iloc[i]
/tmp/ipython-input-164-1544448126.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value


In [167]:
df[df['engine-location']=='rear']

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,updated_prices
126,3,NaN,porsche,gas,std,2.0,hardtop,rwd,rear,89.5,...,mpfi,3.74,2.9,9.5,207,5900,17,25,32528.0,65056.0
127,3,NaN,porsche,gas,std,2.0,hardtop,rwd,rear,89.5,...,mpfi,3.74,2.9,9.5,207,5900,17,25,34028.0,68056.0
128,3,NaN,porsche,gas,std,2.0,convertible,rwd,rear,89.5,...,mpfi,3.74,2.9,9.5,207,5900,17,25,37028.0,74056.0

In [165]:
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,updated_prices
0,3,NaN,alfa-romero,gas,std,2.0,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0,13495.0
1,3,NaN,alfa-romero,gas,std,2.0,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0,16500.0
2,1,NaN,alfa-romero,gas,std,2.0,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0,16500.0
3,2,164,audi,gas,std,4.0,sedan,fwd,front,99.8,...,mpfi,3.19,3.4,10.0,102,5500,24,30,13950.0,13950.0
4,2,164,audi,gas,std,4.0,sedan,4wd,front,99.4,...,mpfi,3.19,3.4,8.0,115,5500,18,22,17450.0,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,4.0,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0,16845.0
201,-1,95,volvo,gas,turbo,4.0,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0,19045.0
202,-1,95,volvo,gas,std,4.0,sedan,rwd,front,109.1,...,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0,21485.0
203,-1,95,volvo,diesel,turbo,4.0,sedan,rwd,front,109.1,...,idi,3.01,3.4,23.0,106,4800,26,27,22470.0,22470.0
204,-1,95,volvo,gas,turbo,4.0,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0,22625.0

In [128]:
df['updated_prices'].iloc[]

np.float64(65056.0)

In [141]:
#f) sorting by car and price
df.sort_values(["make","price"],ascending=False)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,updated_prices
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.000000,NaN
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,idi,3.01,3.4,23.0,106,4800,26,27,22470.000000,NaN
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.000000,NaN
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.000000,NaN
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,mpfi,3.62,3.15,7.5,162,5100,17,22,18950.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.4,10.0,102,5500,24,30,13950.000000,NaN
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,mpfi,3.13,3.4,7.0,160,5500,16,22,13207.129353,NaN
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.000000,NaN
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.000000,NaN
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.000000,NaN

In [131]:
df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'updated_prices', 'length', 'width', 'height',
       'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size',
       'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower',
       'peak-rpm', 'city-mpg', 'highway-mpg', 'price'],
      dtype='object')

In [133]:
df=df[['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height',
       'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size',
       'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower',
       'peak-rpm', 'city-mpg', 'highway-mpg', 'price', 'updated_prices']]

In [149]:
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,updated_prices
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0,NaN
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0,NaN
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0,NaN
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.4,10.0,102,5500,24,30,13950.0,NaN
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.4,8.0,115,5500,18,22,17450.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0,NaN
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0,NaN
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0,NaN
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,idi,3.01,3.4,23.0,106,4800,26,27,22470.0,NaN
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0,NaN

In [130]:
# g)
df['num-of-doors'].unique()

array(['two', 'four', nan], dtype=object)

In [150]:
word_number={'four':4,'two':2}
df['num-of-doors']=df['num-of-doors'].map(word_number)

In [179]:
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,updated_prices
0,3,NaN,alfa-romero,gas,std,2.0,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0,13495.0
1,3,NaN,alfa-romero,gas,std,2.0,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0,16500.0
2,1,NaN,alfa-romero,gas,std,2.0,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0,16500.0
3,2,164,audi,gas,std,4.0,sedan,fwd,front,99.8,...,mpfi,3.19,3.4,10.0,102,5500,24,30,13950.0,13950.0
4,2,164,audi,gas,std,4.0,sedan,4wd,front,99.4,...,mpfi,3.19,3.4,8.0,115,5500,18,22,17450.0,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,4.0,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0,16845.0
201,-1,95,volvo,gas,turbo,4.0,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0,19045.0
202,-1,95,volvo,gas,std,4.0,sedan,rwd,front,109.1,...,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0,21485.0
203,-1,95,volvo,diesel,turbo,4.0,sedan,rwd,front,109.1,...,idi,3.01,3.4,23.0,106,4800,26,27,22470.0,22470.0
204,-1,95,volvo,gas,turbo,4.0,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0,22625.0

In [180]:
# h)   find  all categories of each column
for i in df.columns:
  if df[i].dtype=='object':
    print( i, '----->' ,df[i].unique())

normalized-losses -----> [nan '164' '158' '192' '188' '121' '98' '81' '118' '148' '110' '145' '137'
 '101' '78' '106' '85' '107' '104' '113' '150' '129' '115' '93' '142'
 '161' '153' '125' '128' '122' '103' '168' '108' '194' '231' '119' '154'
 '74' '186' '83' '102' '89' '87' '77' '91' '134' '65' '197' '90' '94'
 '256' '95']
make -----> ['alfa-romero' 'audi' 'bmw' 'chevrolet' 'dodge' 'honda' 'isuzu' 'jaguar'
 'mazda' 'mercedes-benz' 'mercury' 'mitsubishi' 'nissan' 'peugot'
 'plymouth' 'porsche' 'renault' 'saab' 'subaru' 'toyota' 'volkswagen'
 'volvo']
fuel-type -----> ['gas' 'diesel']
aspiration -----> ['std' 'turbo']
body-style -----> ['convertible' 'hatchback' 'sedan' 'wagon' 'hardtop']
drive-wheels -----> ['rwd' 'fwd' '4wd']
engine-location -----> ['front' 'rear']
engine-type -----> ['dohc' 'ohcv' 'ohc' 'l' 'rotor' 'ohcf' 'dohcv']
num-of-cylinders -----> ['four' 'six' 'five' 'three' 'twelve' 'two' 'eight']
fuel-system -----> ['mpfi' '2bbl' 'mfi' '1bbl' 'spfi' '4bbl' 'idi' 'spdi']
bore -----> ['3.47' '2.68' '3.19' '3.13' '3.5' '3.31' '3.62' '2.91' '3.03' '2.97'
 '3.34' '3.6' '2.92' '3.15' '3.43' '3.63' '3.54' '3.08' nan '3.39' '3.76'
 '3.58' '3.46' '3.8' '3.78' '3.17' '3.35' '3.59' '2.99' '3.33' '3.7'
 '3.61' '3.94' '3.74' '2.54' '3.05' '3.27' '3.24' '3.01']
stroke -----> ['2.68' '3.47' '3.4' '2.8' '3.19' '3.39' '3.03' '3.11' '3.23' '3.46' '3.9'
 '3.41' '3.07' '3.58' '4.17' '2.76' '3.15' nan '3.16' '3.64' '3.1' '3.35'
 '3.12' '3.86' '3.29' '3.27' '3.52' '2.19' '3.21' '2.9' '2.07' '2.36'
 '2.64' '3.08' '3.5' '3.54' '2.87']
horsepower -----> ['111' '154' '102' '115' '110' '140' '160' '101' '121' '182' '48' '70'
 '68' '88' '145' '58' '76' '60' '86' '100' '78' '90' '176' '262' '135'
 '84' '64' '120' '72' '123' '155' '184' '175' '116' '69' '55' '97' '152'
 '200' '95' '142' '143' '207' '288' nan '73' '82' '94' '62' '56' '112'
 '92' '161' '156' '52' '85' '114' '162' '134' '106']
peak-rpm -----> ['5000' '5500' '5800' '4250' '5400' '5100' '4800' '6000' '4750' '4650'
 '4200' '4350' '4500' '5200' '4150' '5600' '5900' '5750' nan '5250' '4900'
 '4400' '6600' '5300']

In [181]:
make_encode={'alfa-romero': 1 , 'audi':2, 'bmw':3 , 'chevrolet':4, 'dodge':5, 'honda':6, 'isuzu':7, 'jaguar':8,
 'mazda':9, 'mercedes-benz': 10,'mercury':11, 'mitsubishi':12, 'nissan':13, 'peugot':14, 'plymouth':15,
 'porsche':16, 'renault':17, 'saab':18, 'subaru':19, 'toyota':20, 'volkswagen':21, 'volvo':22}

fuel_type_encode={'diesel':1,'gas':2}
aspiration_encode={'std':1,'turbo':2}
body_style_encode={'convertible':1,'hatchback':2,'sedan':3,'wagon':4,'hardtop':5}
drive_wheels_encode={'rwd':1,'fwd':2,'4wd':3}
engine_location_encode={'front':1,'rear':2}
engine_type_encode={'dohc':1,'ohcv':2,'ohcf':3,'l':4,'rotor':5,'ohc':6,'dohcv':7}
num_of_cylinders_encode={'four':4,'six':6,'five':5,'eight':8,'two':2,'twelve':12,'three':3}
fuel_system_encode={'mpfi':1,'2bbl':2,'mfi':3,'1bbl':4,'spdi':5,'4bbl':6,'idi':7,'spfi':8}

df['make']=df['make'].map(make_encode)
df['fuel-type']=df['fuel-type'].map(fuel_type_encode)
df['aspiration']=df['aspiration'].map(aspiration_encode)
df['body-style']=df['body-style'].map(body_style_encode)
df['drive-wheels']=df['drive-wheels'].map(drive_wheels_encode)
df['engine-location']=df['engine-location'].map(engine_location_encode)
df['engine-type']=df['engine-type'].map(engine_type_encode)
df['num-of-cylinders']=df['num-of-cylinders'].map(num_of_cylinders_encode)
df['fuel-system']=df['fuel-system'].map(fuel_system_encode)

In [182]:
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,updated_prices
0,3,NaN,1,2,1,2.0,1,1,1,88.6,...,1,3.47,2.68,9.0,111,5000,21,27,13495.0,13495.0
1,3,NaN,1,2,1,2.0,1,1,1,88.6,...,1,3.47,2.68,9.0,111,5000,21,27,16500.0,16500.0
2,1,NaN,1,2,1,2.0,2,1,1,94.5,...,1,2.68,3.47,9.0,154,5000,19,26,16500.0,16500.0
3,2,164,2,2,1,4.0,3,2,1,99.8,...,1,3.19,3.4,10.0,102,5500,24,30,13950.0,13950.0
4,2,164,2,2,1,4.0,3,3,1,99.4,...,1,3.19,3.4,8.0,115,5500,18,22,17450.0,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,22,2,1,4.0,3,1,1,109.1,...,1,3.78,3.15,9.5,114,5400,23,28,16845.0,16845.0
201,-1,95,22,2,2,4.0,3,1,1,109.1,...,1,3.78,3.15,8.7,160,5300,19,25,19045.0,19045.0
202,-1,95,22,2,1,4.0,3,1,1,109.1,...,1,3.58,2.87,8.8,134,5500,18,23,21485.0,21485.0
203,-1,95,22,1,2,4.0,3,1,1,109.1,...,7,3.01,3.4,23.0,106,4800,26,27,22470.0,22470.0
204,-1,95,22,2,2,4.0,3,1,1,109.1,...,1,3.78,3.15,9.5,114,5400,19,25,22625.0,22625.0

In [184]:
# highest corelation
A= df.corr()
A

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,updated_prices
symboling,1.000000,0.528667,-0.118794,0.194311,-0.059866,-0.664550,-0.398970,0.041671,0.212471,-0.531954,...,-0.031715,-0.134205,-0.008965,-0.178515,0.071622,0.274573,-0.035823,0.034606,-0.082201,0.023511
normalized-losses,0.528667,1.000000,-0.288361,0.116736,-0.007797,-0.407134,-0.258285,-0.359464,NaN,-0.074362,...,-0.130723,-0.036167,0.065627,-0.132654,0.295772,0.264597,-0.258502,-0.210768,0.203254,0.203254
make,-0.118794,-0.288361,1.000000,-0.113191,0.054265,0.161528,0.154998,0.004317,0.054608,0.078505,...,-0.052203,0.252282,-0.201948,0.138828,-0.053752,-0.218740,0.053642,0.050022,-0.161471,-0.103843
fuel-type,0.194311,0.116736,-0.113191,1.000000,-0.401397,-0.181675,-0.157580,0.132257,0.040070,-0.308346,...,-0.783325,-0.054516,-0.242081,-0.984356,0.165278,0.477314,-0.255963,-0.191392,-0.110207,-0.069717
aspiration,-0.059866,-0.007797,0.054265,-0.401397,1.000000,0.046350,0.021276,-0.066465,-0.057191,0.257611,...,0.401532,0.213090,0.223460,0.295541,0.240443,-0.183829,-0.202362,-0.254416,0.177285,0.115156
num-of-doors,-0.664550,-0.407134,0.161528,-0.181675,0.046350,1.000000,0.450220,0.100344,-0.138613,0.445696,...,0.003553,0.114501,-0.010697,0.165799,-0.124963,-0.242485,-0.020812,-0.044507,0.046051,-0.021324
body-style,-0.398970,-0.258285,0.154998,-0.157580,0.021276,0.450220,1.000000,-0.056886,0.126546,0.368772,...,-0.021611,0.227078,0.000578,0.156686,0.048464,-0.147991,-0.095826,-0.126939,0.178642,0.186378
drive-wheels,0.041671,-0.359464,0.004317,0.132257,-0.066465,0.100344,-0.056886,1.000000,-0.147865,-0.459745,...,0.005352,-0.489022,-0.072695,-0.127479,-0.517822,0.039792,0.449581,0.452220,-0.576866,-0.512825
engine-location,0.212471,NaN,0.054608,0.040070,-0.057191,-0.138613,0.126546,-0.147865,1.000000,-0.187790,...,-0.085177,0.185071,-0.138479,-0.019762,0.317633,0.198415,-0.153487,-0.102026,0.331013,0.672751
wheel-base,-0.531954,-0.074362,0.078505,-0.308346,0.257611,0.445696,0.368772,-0.459745,-0.187790,1.000000,...,0.038998,0.490378,0.161477,0.249786,0.352297,-0.361052,-0.470414,-0.544082,0.583168,0.378940
length,-0.357612,0.023220,0.119584,-0.212679,0.234539,0.393593,0.376842,-0.485649,-0.050989,0.874587,...,-0.077094,0.607480,0.129739,0.158414,0.555003,-0.287325,-0.670909,-0.704662,0.682986,0.513673
width,-0.232919,0.105073,0.003783,-0.233880,0.300567,0.202072,0.191511,-0.470751,-0.051698,0.795144,...,-0.006998,0.559204,0.182956,0.181129,0.642482,-0.219957,-0.642704,-0.677218,0.728699,0.549171
height,-0.541038,-0.432335,0.236233,-0.284631,0.087311,0.547651,0.483675,0.019719,-0.106234,0.589435,...,0.024109,0.176195,-0.056999,0.261214,-0.110711,-0.322272,-0.048640,-0.107358,0.134388,0.061286
curb-weight,-0.227691,0.119893,0.024015,-0.217275,0.324902,0.195683,0.240367,-0.575111,0.050468,0.776386,...,-0.026140,0.649045,0.168929,0.151362,0.751034,-0.266306,-0.757414,-0.797465,0.820825,0.663660
engine-type,-0.076908,-0.194305,-0.097872,-0.081231,0.009535,0.032773,-0.006538,0.266978,-0.159221,-0.172276,...,0.232611,-0.326784,0.288060,0.084099,-0.446890,0.023085,0.385246,0.430779,-0.374659,-0.359199
num-of-cylinders,-0.113129,0.175380,-0.125921,0.024544,-0.047972,-0.016530,0.106245,-0.314006,0.183048,0.339507,...,-0.235028,0.243553,0.008578,-0.020002,0.691633,-0.124434,-0.445837,-0.466666,0.687770,0.614210
engine-size,-0.105790,0.167365,-0.070918,-0.069594,0.108217,0.017519,0.172381,-0.524307,0.196826,0.569329,...,-0.150772,0.594090,0.206675,0.028971,0.810773,-0.244618,-0.653658,-0.677470,0.861752,0.756132
fuel-system,-0.031715,-0.130723,-0.052203,-0.783325,0.401532,0.003553,-0.021611,0.005352,-0.085177,0.038998,...,1.000000,-0.130267,0.337650,0.757384,-0.295594,-0.255324,0.330411,0.274745,-0.112225,-0.123097
bore,-0.134205,-0.036167,0.252282,-0.054516,0.213090,0.114501,0.227078,-0.489022,0.185071,0.490378,...,-0.130267,1.000000,-0.055909,0.005203,0.577273,-0.264269,-0.594584,-0.594572,0.532576,0.493486
stroke,-0.008965,0.065627,-0.201948,-0.242081,0.223460,-0.010697,0.000578,-0.072695,-0.138479,0.161477,...,0.337650,-0.055909,1.000000,0.186170,0.090254,-0.071493,-0.042906,-0.044528,0.082138,0.007018
compression-ratio,-0.178515,-0.132654,0.138828,-0.984356,0.295541,0.165799,0.156686,-0.127479,-0.019762,0.249786,...,0.757384,0.005203,0.186170,1.000000,-0.205874,-0.436221,0.324701,0.265201,0.070990,0.047410
horsepower,0.071622,0.295772,-0.053752,0.165278,0.240443,-0.124963,0.048464,-0.517822,0.317633,0.352297,...,-0.295594,0.577273,0.090254,-0.205874,1.000000,0.130971,-0.803620,-0.770908,0.758714,0.725392
peak-rpm,0.274573,0.264597,-0.218740,0.477314,-0.183829,-0.242485,-0.147991,0.039792,0.198415,-0.361052,...,-0.255324,-0.264269,-0.071493,-0.436221,0.130971,1.000000,-0.113788,-0.054257,-0.100960,0.003090
city-mpg,-0.035823,-0.258502,0.053642,-0.255963,-0.202362,-0.020812,-0.095826,0.449581,-0.153487,-0.470414,...,0.330411,-0.594584,-0.042906,0.324701,-0.803620,-0.113788,1.000000,0.971337,-0.667449,-0.586074
highway-mpg,0.034606,-0.210768,0.050022,-0.191392,-0.254416,-0.044507,-0.126939,0.452220,-0.102026,-0.544082,...,0.274745,-0.594572,-0.044528,0.265201,-0.770908,-0.054257,0.971337,1.000000,-0.690526,-0.582859
price,-0.082201,0.203254,-0.161471,-0.110207,0.177285,0.046051,0.178642,-0.576866,0.331013,0.583168,...,-0.112225,0.532576,0.082138,0.070990,0.758714,-0.100960,-0.667449,-0.690526,1.000000,0.920524
updated_prices,0.023511,0.203254,-0.103843,-0.069717,0.115156,-0.021324,0.186378,-0.512825,0.672751,0.378940,...,-0.123097,0.493486,0.007018,0.047410,0.725392,0.003090,-0.586074,-0.582859,0.920524,1.000000

In [188]:
# print top highest corelation of price
A['price'].sort_values(ascending=False)

price                1.000000
updated_prices       0.920524
engine-size          0.861752
curb-weight          0.820825
horsepower           0.758714
width                0.728699
num-of-cylinders     0.687770
length               0.682986
wheel-base           0.583168
bore                 0.532576
engine-location      0.331013
normalized-losses    0.203254
body-style           0.178642
aspiration           0.177285
height               0.134388
stroke               0.082138
compression-ratio    0.070990
num-of-doors         0.046051
symboling           -0.082201
peak-rpm            -0.100960
fuel-type           -0.110207
fuel-system         -0.112225
make                -0.161471
engine-type         -0.374659
drive-wheels        -0.576866
city-mpg            -0.667449
highway-mpg         -0.690526
Name: price, dtype: float64

In [178]:
GermanCars = {
    'Company': ['Ford', 'Mercedes', 'BMW', 'Audi'],
    'Price': [23845, 171995, 135925, 71400]
}
JapaneseCars = {
    'Company': ['Toyota', 'Honda', 'Nisaan', 'Mitsubishi'],
    'Price': [29995, 23600, 61500, 58900]
}
a = pd.DataFrame(GermanCars)
b = pd.DataFrame(JapaneseCars)
concatingbyROW = pd.concat([a, b], axis=0, ignore_index=True)
concatbyROW= pd.concat([a, b], axis=1)
print(concatingbyROW)
print("---------------------------------")
print(concatbyROW)

      Company   Price
0        Ford   23845
1    Mercedes  171995
2         BMW  135925
3        Audi   71400
4      Toyota   29995
5       Honda   23600
6      Nisaan   61500
7  Mitsubishi   58900
---------------------------------
    Company   Price     Company  Price
0      Ford   23845      Toyota  29995
1  Mercedes  171995       Honda  23600
2       BMW  135925      Nisaan  61500
3      Audi   71400  Mitsubishi  58900

In [190]:
# j) first 15 and last 15
df.head(15)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,updated_prices
0,3,NaN,1,2,1,2.0,1,1,1,88.6,...,1,3.47,2.68,9.0,111,5000,21,27,13495.000000,13495.000000
1,3,NaN,1,2,1,2.0,1,1,1,88.6,...,1,3.47,2.68,9.0,111,5000,21,27,16500.000000,16500.000000
2,1,NaN,1,2,1,2.0,2,1,1,94.5,...,1,2.68,3.47,9.0,154,5000,19,26,16500.000000,16500.000000
3,2,164,2,2,1,4.0,3,2,1,99.8,...,1,3.19,3.4,10.0,102,5500,24,30,13950.000000,13950.000000
4,2,164,2,2,1,4.0,3,3,1,99.4,...,1,3.19,3.4,8.0,115,5500,18,22,17450.000000,17450.000000
5,2,NaN,2,2,1,2.0,3,2,1,99.8,...,1,3.19,3.4,8.5,110,5500,19,25,15250.000000,15250.000000
6,1,158,2,2,1,4.0,3,2,1,105.8,...,1,3.19,3.4,8.5,110,5500,19,25,17710.000000,17710.000000
7,1,NaN,2,2,1,4.0,4,2,1,105.8,...,1,3.19,3.4,8.5,110,5500,19,25,18920.000000,18920.000000
8,1,158,2,2,2,4.0,3,2,1,105.8,...,1,3.13,3.4,8.3,140,5500,17,20,23875.000000,23875.000000
9,0,NaN,2,2,2,2.0,2,3,1,99.5,...,1,3.13,3.4,7.0,160,5500,16,22,13207.129353,13207.129353
10,2,192,3,2,1,2.0,3,1,1,101.2,...,1,3.5,2.8,8.8,101,5800,23,29,16430.000000,16430.000000
11,0,192,3,2,1,4.0,3,1,1,101.2,...,1,3.5,2.8,8.8,101,5800,23,29,16925.000000,16925.000000
12,0,188,3,2,1,2.0,3,1,1,101.2,...,1,3.31,3.19,9.0,121,4250,21,28,20970.000000,20970.000000
13,0,188,3,2,1,4.0,3,1,1,101.2,...,1,3.31,3.19,9.0,121,4250,21,28,21105.000000,21105.000000
14,1,NaN,3,2,1,4.0,3,1,1,103.5,...,1,3.31,3.19,9.0,121,4250,20,25,24565.000000,24565.000000

In [191]:
df.tail(15)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,updated_prices
190,3,256,21,2,1,2.0,2,2,1,94.5,...,1,3.19,3.4,8.5,90,5500,24,29,9980.0,9980.0
191,0,NaN,21,2,1,4.0,3,2,1,100.4,...,1,3.19,3.4,8.5,110,5500,19,24,13295.0,13295.0
192,0,NaN,21,1,2,4.0,3,2,1,100.4,...,7,3.01,3.4,23.0,68,4500,33,38,13845.0,13845.0
193,0,NaN,21,2,1,4.0,4,2,1,100.4,...,1,3.19,3.4,9.0,88,5500,25,31,12290.0,12290.0
194,-2,103,22,2,1,4.0,3,1,1,104.3,...,1,3.78,3.15,9.5,114,5400,23,28,12940.0,12940.0
195,-1,74,22,2,1,4.0,4,1,1,104.3,...,1,3.78,3.15,9.5,114,5400,23,28,13415.0,13415.0
196,-2,103,22,2,1,4.0,3,1,1,104.3,...,1,3.78,3.15,9.5,114,5400,24,28,15985.0,15985.0
197,-1,74,22,2,1,4.0,4,1,1,104.3,...,1,3.78,3.15,9.5,114,5400,24,28,16515.0,16515.0
198,-2,103,22,2,2,4.0,3,1,1,104.3,...,1,3.62,3.15,7.5,162,5100,17,22,18420.0,18420.0
199,-1,74,22,2,2,4.0,4,1,1,104.3,...,1,3.62,3.15,7.5,162,5100,17,22,18950.0,18950.0
200,-1,95,22,2,1,4.0,3,1,1,109.1,...,1,3.78,3.15,9.5,114,5400,23,28,16845.0,16845.0
201,-1,95,22,2,2,4.0,3,1,1,109.1,...,1,3.78,3.15,8.7,160,5300,19,25,19045.0,19045.0
202,-1,95,22,2,1,4.0,3,1,1,109.1,...,1,3.58,2.87,8.8,134,5500,18,23,21485.0,21485.0
203,-1,95,22,1,2,4.0,3,1,1,109.1,...,7,3.01,3.4,23.0,106,4800,26,27,22470.0,22470.0
204,-1,95,22,2,2,4.0,3,1,1,109.1,...,1,3.78,3.15,9.5,114,5400,19,25,22625.0,22625.0

2nd csv file

In [193]:
ff=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/COLLAB FILES CSV/phone_data.csv")
ff

     index            date  duration  item    month   network network_type
0        0  15/10/14 06:58    34.429  data  2014-11      data         data
1        1  15/10/14 06:58    13.000  call  2014-11  Vodafone       mobile
2        2  15/10/14 14:46    23.000  call  2014-11    Meteor       mobile
3        3  15/10/14 14:48     4.000  call  2014-11     Tesco       mobile
4        4  15/10/14 17:27     4.000  call  2014-11     Tesco       mobile
..     ...             ...       ...   ...      ...       ...          ...
825    825  13/03/15 00:38     1.000   sms  2015-03     world        world
826    826  13/03/15 00:39     1.000   sms  2015-03  Vodafone       mobile
827    827  13/03/15 06:58    34.429  data  2015-03      data         data
828    828  14/03/15 00:13     1.000   sms  2015-03     world        world
829    829  14/03/15 00:16     1.000   sms  2015-03     world        world

[830 rows x 7 columns]

In [194]:
ff.describe()

            index      duration
count  830.000000    830.000000
mean   414.500000    117.804036
std    239.744656    444.129560
min      0.000000      1.000000
25%    207.250000      1.000000
50%    414.500000     24.500000
75%    621.750000     55.000000
max    829.000000  10528.000000

In [197]:
# a Perform outlier removal in the duration column in the given dataset. Explain the factors to be considered while outlier treatment.

In [199]:
# b. Plot the BoxPlot and DistPlot post outlier removal.

In [201]:
# c. Draw important inferences and conclusions from the created Plots and explain them as a Data Analyst.

In [203]:
# d. Give a Five-number summary of every column on the dataset.